services:
  - type: web
    name: app-builder-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GITHUB_OWNER
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: USE_MOCK_DATA
        value: false 