# 1.
name: Android Build

# 2.
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  workflow_dispatch:  # Allow manual triggering

# 3.
jobs:
  build-android:
    runs-on: ubuntu-latest  # Ubuntu is sufficient for Android builds

    # 4.
    steps:
      # 5.
      - name: Clone repository
        uses: actions/checkout@v4

      # 6.
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"  # Updated to a more stable JDK version

      # 7.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'
          cache: true  # Enable Flutter cache for faster builds

      # 8.
      - name: Get Flutter packages
        run: |
          flutter pub get

      # 9.


      # 10.
     

      # 11.
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 12.
      - name: Build Android APK and App Bundle
        run: |
          echo "Building APK..."
          flutter build apk --release --dart-define=APP_NAME="WebView App" --dart-define=WEBVIEW_URL="https://flutter.dev"
          if [ $? -ne 0 ]; then
            echo "APK build failed"
            exit 1
          fi
          
          echo "Building App Bundle (AAB)..."
          flutter build appbundle --release --dart-define=APP_NAME="WebView App" --dart-define=WEBVIEW_URL="https://flutter.dev"
          if [ $? -ne 0 ]; then
            echo "App Bundle build failed"
            exit 1
          fi
        shell: bash

      # 13.
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7  # Keep artifacts for 7 days

      # 14.
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7  # Keep artifacts for 7 days