name: Android Build

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to load in WebView'
        required: false
        default: 'https://flutter.dev'
      app_name:
        description: 'Application display name'
        required: false
        default: 'WebView App'
      build_id:
        description: 'Build ID for tracking in Firestore'
        required: false
        default: ''
  repository_dispatch:
    types: [build-android-request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      BUILD_ID: ${{ github.event.inputs.build_id || github.event.client_payload.build_id || github.run_id }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'
          cache: true

      - name: Get Flutter packages
        run: flutter pub get

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Android APK and App Bundle
        run: |
          flutter clean
          
          APP_NAME="${{ github.event.inputs.app_name || github.event.client_payload.app_name || 'WebView App' }}"
          WEBVIEW_URL="${{ github.event.inputs.url || github.event.client_payload.url || 'https://flutter.dev' }}"
          
          echo "Building with APP_NAME: $APP_NAME"
          echo "Building with WEBVIEW_URL: $WEBVIEW_URL"
         
          ESCAPED_APP_NAME=$(echo "$APP_NAME" | sed 's/[\/&]/\\&/g')
          sed -i "s/<string name=\"app_name\">.*<\/string>/<string name=\"app_name\">$ESCAPED_APP_NAME<\/string>/g" android/app/src/main/res/values/strings.xml
          
          flutter build apk --release \
            --dart-define=APP_NAME="$APP_NAME" \
            --dart-define=WEBVIEW_URL="$WEBVIEW_URL"
          
          flutter build appbundle --release \
            --dart-define=APP_NAME="$APP_NAME" \
            --dart-define=WEBVIEW_URL="$WEBVIEW_URL"

      # Setup Python for Firebase uploads
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      # Install required Python packages
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      # Upload APK and AAB to Firebase Storage using Python script
      - name: Upload to Firebase Storage
        if: success()
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          BUILD_ID: ${{ env.BUILD_ID }}
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          # Set the explicit bucket name as provided
          FIREBASE_STORAGE_BUCKET: "trader-35173.firebasestorage.app"
        run: |
          # Debug environment variables (masked for security)
          echo "FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID"
          echo "FIREBASE_SERVICE_ACCOUNT_BASE64 is set: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 != '' }}"
          echo "FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET"
          echo "BUILD_ID: $BUILD_ID"
          
          echo "Uploading artifacts to Firebase Storage..."
          python scripts/upload_to_firebase.py
          
      # Update Firestore with build information
      - name: Update Firestore
        if: env.BUILD_ID != '' && env.APK_URL != ''
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          BUILD_ID: ${{ env.BUILD_ID }}
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          FIREBASE_STORAGE_BUCKET: "trader-35173.firebasestorage.app"
        run: |
          echo "Updating Firestore document for build $BUILD_ID..."
          
          # Create a Python script to update Firestore
          cat > /tmp/update_firestore.py << EOL
